-- Enable the pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Create the brand_kits table
CREATE TABLE IF NOT EXISTS brand_kits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brandId UUID NOT NULL UNIQUE,
    url TEXT NOT NULL,
    name TEXT,
    kit_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_brand_kits_brandid ON brand_kits(brandId);
CREATE INDEX IF NOT EXISTS idx_brand_kits_url ON brand_kits(url);